Metrics/BlockLength:
  Exclude:
    - 'roda_api_generator.gemspec'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Layout/SpaceBeforeSemicolon:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%w': '()'
